# Generated by Django 6.0.6 on 2026-06-08 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_rate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='char_code',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
