# Generated by Django 6.0.6 on 2026-06-08 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_rate', '0002_alter_currency_char_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='char_code',
        ),
    ]
