# Generated by Django 6.0.6 on 2026-06-16 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits_tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serie',
            old_name='day_count',
            new_name='best_day_count',
        ),
        migrations.RemoveField(
            model_name='serie',
            name='is_best_serie',
        ),
        migrations.RemoveField(
            model_name='serie',
            name='is_current_serie',
        ),
        migrations.AddField(
            model_name='serie',
            name='current_day_count',
            field=models.IntegerField(default=0),
        ),
    ]
